name: CDK Deploy on AWS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        permissions:
            contents: read
            id-token: write
        env:
            APP_NAME: ${{ vars.APP_NAME }}
            ACCOUNT_AWS: ${{ vars.ACCOUNT_AWS }}
            REGION_AWS: ${{ vars.REGION_AWS }}
            DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
            SUBDOMAIN_NAME: ${{ vars.SUBDOMAIN_NAME }}
            EC2_HOST: ${{ vars.EC2_HOST }}
                        
        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v4
      
            - name: Instalar .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ vars.VERSION_DOTNET }}
      
            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.VERSION_NODEJS }}
                                                      
            - name: Instalar AWS CDK
              run: npm install -g aws-cdk
                                          
            - name: Publish .NET Application
              run: dotnet publish /p:PublishDir=../publish /p:PublishReadyToRun=true -r linux-arm64 --self-contained true 
              
            - name: Copy files to EC2
              env:
                  EC2_HOST: ${{ vars.EC2_HOST }}
                  EC2_USERNAME: ${{ vars.EC2_USERNAME }}
                  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
                  WEBAPP_DIRECTORY: ${{ vars.WEBAPP_DIRECTORY }}
                  WEBAPP_SERVICE: ${{ vars.WEBAPP_SERVICE }}
                  WEBAPP_EXECSTART: ${{ vars.WEBAPP_EXECSTART }}
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
                
                echo "$EC2_SSH_KEY" > ssh_key.pem
                chmod 600 ssh_key.pem
                
                # En caso de que ya se haya desplegado alguna vez la aplicación, se detiene y se eliminan los archivos antiguos...
                ssh -i ssh_key.pem $EC2_USERNAME@$EC2_HOST "WEBAPP_SERVICE=$WEBAPP_SERVICE WEBAPP_DIRECTORY=$WEBAPP_DIRECTORY" '
                    sudo systemctl stop $WEBAPP_SERVICE || true
                    rm -rf ~/$WEBAPP_DIRECTORY/*
                '
                
                # Se copian las piezas publicadas en directorio remoto de instancia EC2...
                scp -i ssh_key.pem -r ./publish/* $EC2_USERNAME@$EC2_HOST:~/$WEBAPP_DIRECTORY
                
                # Se copia el archivo service...
                scp -i ssh_key.pem ./$WEBAPP_SERVICE.service $EC2_USERNAME@$EC2_HOST:~/$WEBAPP_DIRECTORY 
                
                # Se copia el archivo service...
                scp -i ssh_key.pem ./$WEBAPP_SERVICE.conf $EC2_USERNAME@$EC2_HOST:~/$WEBAPP_DIRECTORY 
                
                # Se inicializa el web service...
                ssh -i ssh_key.pem $EC2_USERNAME@$EC2_HOST "WEBAPP_SERVICE=$WEBAPP_SERVICE WEBAPP_DIRECTORY=$WEBAPP_DIRECTORY WEBAPP_EXECSTART=$WEBAPP_EXECSTART" '
                    sudo mv -f ~/$WEBAPP_DIRECTORY/$WEBAPP_SERVICE.service /etc/systemd/system/
                    sudo chmod +x ~/$WEBAPP_DIRECTORY/$WEBAPP_EXECSTART
                    sudo systemctl daemon-reload
                    sudo systemctl enable $WEBAPP_SERVICE
                    sudo systemctl restart $WEBAPP_SERVICE
                    
                    sudo mv -f ~/$WEBAPP_DIRECTORY/$WEBAPP_SERVICE.conf /etc/nginx/conf.d/
                    sudo systemctl restart nginx 
                '
                
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
              with:
                  aws-region: ${{ vars.REGION_AWS }}
                  role-to-assume: ${{ vars.ARN_GITHUB_ROLE }}
                
            - name: CDK Synth
              working-directory: ${{ vars.DIRECTORIO_CDK }}
              run: cdk synth
              
            - name: CDK Diff
              working-directory: ${{ vars.DIRECTORIO_CDK }}
              run: cdk --app cdk.out diff
              
            - name: CDK Deploy
              working-directory: ${{ vars.DIRECTORIO_CDK }}
              run: cdk --app cdk.out deploy --require-approval never