name: CDK Deploy on AWS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        permissions:
            contents: read
            id-token: write
        env:
            APP_NAME: ${{ vars.APP_NAME }}
            ACCOUNT_AWS: ${{ vars.ACCOUNT_AWS }}
            REGION_AWS: ${{ vars.REGION_AWS }}
                        
        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v4
      
            - name: Instalar .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ vars.VERSION_DOTNET }}
      
            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.VERSION_NODEJS }}
                                                      
            - name: Instalar AWS CDK
              run: npm install -g aws-cdk
                                          
            - name: Publish .NET Application
              run: dotnet publish /p:PublishDir=../publish /p:PublishReadyToRun=true -r linux-arm64 --self-contained true 
              
            - name: Copy files to EC2
              env:
                  EC2_HOST: ${{ vars.EC2_HOST }}
                  EC2_USERNAME: ${{ vars.EC2_USERNAME }}
                  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
                
                echo "$EC2_SSH_KEY" > ssh_key.pem
                chmod 600 ssh_key.pem
                
                scp -i ssh_key.pem -r ./publish/* $EC2_USERNAME:~/$APP_NAME